#!/bin/sh
# Copyright 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0
#
# Install packages from bindep.txt using the system package manager.

set -e

SCRIPT_DIR=$(dirname "$0")
BINDEP_FILE="${1:-/bindep.txt}"

"$SCRIPT_DIR/install-packages" $("$SCRIPT_DIR/uvx" bindep -b -f "$BINDEP_FILE")
"$SCRIPT_DIR/uv" cache clean
rm -rf ~/.local/share/uv
