#!/bin/sh
# Copyright 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

set -e

SCRIPT_DIR=$(dirname "$0")
BINDEP_FILE="${1:-/bindep.txt}"

export UV_LINK_MODE=copy
export UV_PYTHON_DOWNLOADS=never
"$SCRIPT_DIR/install-packages" $("$SCRIPT_DIR/uvx" bindep -b -f "$BINDEP_FILE")
